apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: .just
    contents:
      - path: .
        git:
          url: https://github.com/pschmitt/android-app-ci
          ref: main
        includePaths:
          - just/common.just
          - just/single-module.just
        newRootPath: just
